GET http://localhost:5000/api

###

POST http://localhost:5000/api/register
content-type: application/json

{
    "username": "",
    "password": ""
}

###
POST http://localhost:5000/api/verify
content-type: application/json

{
    "username": "",
    "password": "",
    "userId": "",
    "token": ""
}

###
POST http://localhost:5000/api/validate
content-type: application/json

{
    "username": "",
    "password": "",
    "userId": "",
    "token": ""
}